version: "3.9"

services:
  server:
    image: "golang:1.20"
    depends_on:
      - postgres
    build: .
    restart: on-failure
    ports:
      - "3000:3000"
  postgres:
    restart: on-failure
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local